<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Informasi_xui.UI.Button-BACKGROUNDah</name>
   <tag></tag>
   <elementGuidId>5244fad6-16d4-4c97-9f07-cff52a748b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Button-BACKGROUND:ah:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;O K&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44aa8d9a-d377-42a1-a578-9a4bd3e36586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Button-BACKGROUND:ah:</value>
      <webElementGuid>c24638ac-8cd0-43de-b10c-bb0d52365609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-button-background     xui-custom</value>
      <webElementGuid>25257cee-c668-4c0e-8eee-c8f8f28370f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-BACKGROUND:ah:&quot;)</value>
      <webElementGuid>80e8f7e1-7df2-414a-bfdd-83ae795e273d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Button-BACKGROUND:ah:']</value>
      <webElementGuid>40ad380a-fa30-4e3e-8c6b-69f80d37c663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='xui.UI.Button:ah:']/div</value>
      <webElementGuid>52f66bea-ce89-49a8-aa9b-0358cf336bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[18]/span/span/div[2]/div/div/div/button/div</value>
      <webElementGuid>3b0edeee-cbf7-4a2f-a751-96bc50acde6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Button-BACKGROUND:ah:']</value>
      <webElementGuid>6327d2b6-436b-48d1-bfac-ac360c241140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
