<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes_1 (1)</name>
   <tag></tag>
   <elementGuidId>34b4c792-53ac-463b-bf5a-028d4cd15e27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Button-CAPTION:v:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6aecb56d-b917-486d-ba1a-8e564a0efa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Button-CAPTION:v:</value>
      <webElementGuid>f44524e4-c2b8-4dd8-9f35-bed3205a1f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-button-caption     xui-custom</value>
      <webElementGuid>e2133b0d-d846-46ab-bfd7-db995d68d60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>5b6fb261-b1e8-4be7-a039-a116af01f480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-CAPTION:v:&quot;)</value>
      <webElementGuid>b222729d-9f76-47ca-8fb4-a49887e5b4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Button-CAPTION:v:']</value>
      <webElementGuid>4c3d5407-0938-440f-9c6c-63bc9ea55e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='xui.UI.Button:v:']/span[2]</value>
      <webElementGuid>4ddebf4d-6d88-4016-8c9b-1b8817d06378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN OUT'])[1]/following::span[12]</value>
      <webElementGuid>3ddd719a-f2b8-4cef-a56e-0a14098829a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Window Size'])[2]/following::span[30]</value>
      <webElementGuid>91f7445a-d243-43e8-bba0-df94ae06f128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::span[3]</value>
      <webElementGuid>5f8de77a-b8d7-4b76-a709-6e7fed9e7aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure to Sign Out ?'])[1]/preceding::span[7]</value>
      <webElementGuid>b6d90353-7180-4fa5-8e29-bf21e7ad23a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]/span/span/div[2]/div/div/div/button/span[2]</value>
      <webElementGuid>70481fdc-d37e-4423-a33e-a514a991dfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Button-CAPTION:v:' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>0e5e85cd-4827-4417-afc2-57c466bb67b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
