<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>694a9552-700c-4731-a4ab-c77d0bb292ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Block-PANEL:s:']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>412c9f5f-881b-46eb-aad6-7eaf0bda39e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e11be454-df83-4988-a29b-39d391e7724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c4c791d-76cf-4383-b941-e9e3f502f68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de68f844-b575-4e71-ab3f-cfba3cb7b04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>40cb705e-eb4b-4658-a104-f62c008d763f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a969d80e-8e0c-478c-ac2b-1a9812adcaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7520d05c-90f0-4a7f-a8b5-1fc246366db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c284aa42-e3a5-425f-bbd7-2953c8fd2bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>42f7f2f2-6a5f-497a-a665-0e61554dbede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.src='../api/app/Views/Preview.html?_rand_=7kivhz36&amp;cabang=370&amp;file=pdf&amp;grpField=cash_outlet&amp;grpFieldDesc=Kantor%2520Kas&amp;grpFieldFrom=001&amp;grpFieldTo=001&amp;grpTable=mn_para_branch&amp;grpTableDesc=brnm&amp;grpTableField=brncd&amp;grpTableFilter=brlvl%2520%253D%2520%273%27&amp;kategori=3&amp;key=ab0uiol8&amp;method=POST&amp;mode=I&amp;module=SVRP0058&amp;orderBy=1&amp;page=all&amp;pengguna2=&amp;pnamabank=BANK%2520SINERGI%2520PRAKARSA%2520UTAMA&amp;progid=http%3A%2F%2F192.168.1.239%3A8080%2FCoreMain%2Fapi%2Fpublic%2Fwebarb%2Fmain%2Freport%2F&amp;teler1=&amp;teler2=&amp;tglquery=%222025-01-14T00%3A00%3A00.000+0700%22&amp;title=LAPORAN%2520PEMBATALAN%2520BLOKIR%2520DANA%2520REKENING%2520MEMBUTUHKAN%2520PERSETUJUAN&amp;Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlKyIsImlhdCI6MTc1Mzc4MTc1NywiZXhwIjoxNzUzODY4MTU3LCJicm4iOiIzNzAiLCJvZmMiOm51bGwsInVpZCI6MjIzNSwiaW5tIjoiSFVCIiwidXNyIjoiSFVCRVJUVVMiLCJ1Zm4iOiJIVUJFUlRVUyBLIDEiLCJkZXAiOjY5LCJsdmwiOjYwNzQsImFkbSI6ZmFsc2UsIm9wciI6ZmFsc2UsIm9kdCI6IjIwMjUtMDEtMTQiLCJjdHIiOiJZIiwiY3NsIjoiMDAwIiwibG9nIjoiMjAyNS0wNy0yOSAxNjozNTo1NyIsImNpZCI6Img3MmZoYnp3IiwicGlkIjoiOTBoazhyMzEiLCJpcGEiOiIxOTIuMTY4LjEwLjQzIiwiYXBwIjoiQ1AiLCJlbmMiOmZhbHNlLCJ2ZXIiOiIyMDI1LTA3LTA3In0.iXyEMAz2r1b3x4eJMb5yPHkwiAP8_aVoH2UzgsVWvE4'.replace('&amp;','#')</value>
      <webElementGuid>cda04ed9-9a61-46c9-94bc-d21f246a6189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../api/app/Views/Preview.html?_rand_=7kivhz36#cabang=370&amp;file=pdf&amp;grpField=cash_outlet&amp;grpFieldDesc=Kantor%2520Kas&amp;grpFieldFrom=001&amp;grpFieldTo=001&amp;grpTable=mn_para_branch&amp;grpTableDesc=brnm&amp;grpTableField=brncd&amp;grpTableFilter=brlvl%2520%253D%2520%273%27&amp;kategori=3&amp;key=ab0uiol8&amp;method=POST&amp;mode=I&amp;module=SVRP0058&amp;orderBy=1&amp;page=all&amp;pengguna2=&amp;pnamabank=BANK%2520SINERGI%2520PRAKARSA%2520UTAMA&amp;progid=http%3A%2F%2F192.168.1.239%3A8080%2FCoreMain%2Fapi%2Fpublic%2Fwebarb%2Fmain%2Freport%2F&amp;teler1=&amp;teler2=&amp;tglquery=%222025-01-14T00%3A00%3A00.000+0700%22&amp;title=LAPORAN%2520PEMBATALAN%2520BLOKIR%2520DANA%2520REKENING%2520MEMBUTUHKAN%2520PERSETUJUAN&amp;Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlKyIsImlhdCI6MTc1Mzc4MTc1NywiZXhwIjoxNzUzODY4MTU3LCJicm4iOiIzNzAiLCJvZmMiOm51bGwsInVpZCI6MjIzNSwiaW5tIjoiSFVCIiwidXNyIjoiSFVCRVJUVVMiLCJ1Zm4iOiJIVUJFUlRVUyBLIDEiLCJkZXAiOjY5LCJsdmwiOjYwNzQsImFkbSI6ZmFsc2UsIm9wciI6ZmFsc2UsIm9kdCI6IjIwMjUtMDEtMTQiLCJjdHIiOiJZIiwiY3NsIjoiMDAwIiwibG9nIjoiMjAyNS0wNy0yOSAxNjozNTo1NyIsImNpZCI6Img3MmZoYnp3IiwicGlkIjoiOTBoazhyMzEiLCJpcGEiOiIxOTIuMTY4LjEwLjQzIiwiYXBwIjoiQ1AiLCJlbmMiOmZhbHNlLCJ2ZXIiOiIyMDI1LTA3LTA3In0.iXyEMAz2r1b3x4eJMb5yPHkwiAP8_aVoH2UzgsVWvE4</value>
      <webElementGuid>0ebe0953-2dae-4ad2-b3e6-76adc29d05d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Block-PANEL:s:&quot;)/iframe[1]</value>
      <webElementGuid>7ed34223-0c77-4d7a-8ad8-00ada0a578ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Block-PANEL:s:']/iframe</value>
      <webElementGuid>90f13a9a-ca6e-42f1-b3af-f8a5d7f489a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPORAN PEMBATALAN BLOKIR DANA REKENING MEMBUTUHKAN PERSETUJUAN (Print Preview)'])[1]/following::iframe[1]</value>
      <webElementGuid>647fb5f1-47b0-4528-b02f-1b44674ce4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXCEL'])[1]/following::iframe[1]</value>
      <webElementGuid>ddf8441a-0b67-41c3-86cf-c8a9894a515f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVRP0058'])[1]/preceding::iframe[1]</value>
      <webElementGuid>f7b0aecb-3cd5-4261-9fb0-d8484ac74834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVRP0058'])[2]/preceding::iframe[1]</value>
      <webElementGuid>d434aab7-9f39-45ee-ab33-850760518505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>375f942c-4a11-4f9f-851b-dff414205462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../api/app/Views/Preview.html?_rand_=7kivhz36#cabang=370&amp;file=pdf&amp;grpField=cash_outlet&amp;grpFieldDesc=Kantor%2520Kas&amp;grpFieldFrom=001&amp;grpFieldTo=001&amp;grpTable=mn_para_branch&amp;grpTableDesc=brnm&amp;grpTableField=brncd&amp;grpTableFilter=brlvl%2520%253D%2520%273%27&amp;kategori=3&amp;key=ab0uiol8&amp;method=POST&amp;mode=I&amp;module=SVRP0058&amp;orderBy=1&amp;page=all&amp;pengguna2=&amp;pnamabank=BANK%2520SINERGI%2520PRAKARSA%2520UTAMA&amp;progid=http%3A%2F%2F192.168.1.239%3A8080%2FCoreMain%2Fapi%2Fpublic%2Fwebarb%2Fmain%2Freport%2F&amp;teler1=&amp;teler2=&amp;tglquery=%222025-01-14T00%3A00%3A00.000+0700%22&amp;title=LAPORAN%2520PEMBATALAN%2520BLOKIR%2520DANA%2520REKENING%2520MEMBUTUHKAN%2520PERSETUJUAN&amp;Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlKyIsImlhdCI6MTc1Mzc4MTc1NywiZXhwIjoxNzUzODY4MTU3LCJicm4iOiIzNzAiLCJvZmMiOm51bGwsInVpZCI6MjIzNSwiaW5tIjoiSFVCIiwidXNyIjoiSFVCRVJUVVMiLCJ1Zm4iOiJIVUJFUlRVUyBLIDEiLCJkZXAiOjY5LCJsdmwiOjYwNzQsImFkbSI6ZmFsc2UsIm9wciI6ZmFsc2UsIm9kdCI6IjIwMjUtMDEtMTQiLCJjdHIiOiJZIiwiY3NsIjoiMDAwIiwibG9nIjoiMjAyNS0wNy0yOSAxNjozNTo1NyIsImNpZCI6Img3MmZoYnp3IiwicGlkIjoiOTBoazhyMzEiLCJpcGEiOiIxOTIuMTY4LjEwLjQzIiwiYXBwIjoiQ1AiLCJlbmMiOmZhbHNlLCJ2ZXIiOiIyMDI1LTA3LTA3In0.iXyEMAz2r1b3x4eJMb5yPHkwiAP8_aVoH2UzgsVWvE4']</value>
      <webElementGuid>80996611-e564-4cbc-8629-69c0ea607147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
