<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sampai_xui.UI.ComboInput-RBTNq</name>
   <tag></tag>
   <elementGuidId>f5e383b8-40ed-43a7-a12c-2c3dbbb47dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='xui.UI.ComboInput-RBTN:q:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=group[name=&quot;Group&quot;i] >> internal:role=button >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d48892f-0714-4b22-a9b3-33f5eaa07b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-RBTN:q:</value>
      <webElementGuid>aa381acf-b31b-4101-8a98-bd16108f5645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-button xui-comboinput-rbtn xui-ui-unselectable xui-ui-btn xui-uibar xui-uigradient xui-nofocus xui-uiborder-radius-tr xui-uiborder-radius-br xui-uiborder-noradius-l     xui-custom</value>
      <webElementGuid>f5569e33-c754-422c-acb9-12c830797311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-RBTN:q:&quot;)</value>
      <webElementGuid>7f018504-f4dc-4493-9b56-f70a5f2a3b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='xui.UI.ComboInput-RBTN:q:']</value>
      <webElementGuid>7fa5c1a1-441e-4470-aa1e-8f7e22c7725d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ComboInput-BORDER:q:']/button</value>
      <webElementGuid>515775e7-69ba-430b-b7e2-70b19ec83b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sampai'])[1]/following::button[3]</value>
      <webElementGuid>236a5503-18e2-43bd-a650-3e9d05906e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari'])[1]/following::button[7]</value>
      <webElementGuid>1f7f4a41-c030-4c5b-b7e6-92307bb5a1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Group'])[1]/preceding::button[2]</value>
      <webElementGuid>e5e69243-2462-49b8-8cf7-34c3ae8bf0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari'])[2]/preceding::button[2]</value>
      <webElementGuid>a1583cc1-15e0-4b7f-b248-bbd55cf91d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/span[3]/button</value>
      <webElementGuid>a39f5e5e-0785-4d82-a598-7f1090c24e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'xui.UI.ComboInput-RBTN:q:']</value>
      <webElementGuid>3ea5c57b-33d8-40ca-83a7-bf5aff7f3ca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
