<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berdasarkan</name>
   <tag></tag>
   <elementGuidId>b342ef77-8989-4259-918f-a40d0d36b8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Group-PANEL:h:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^BerdasarkanNOMOR REKENING$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34e78cd2-86ee-4b50-b4ee-e2bc9caafa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Group-PANEL:h:</value>
      <webElementGuid>6218e31f-fd22-47d4-8b8f-694bade5cc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-group-panel xui-uicontainer xui-uiborder-radius-bl xui-uiborder-radius-br     xui-custom</value>
      <webElementGuid>4f5af3c3-f7fd-4a90-a3b4-1e0e05f78e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berdasarkan</value>
      <webElementGuid>f0d8ef38-4309-4d73-8757-4b7b3136335a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Group-PANEL:h:&quot;)</value>
      <webElementGuid>6ae46a23-3023-419f-92e6-870370eba2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Group-PANEL:h:']</value>
      <webElementGuid>72115c81-3799-4826-9235-603df1c4e99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='xui.UI.Group-BORDER:h:']/div</value>
      <webElementGuid>a6f931a2-da35-4fea-ab5f-855d36438b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutan'])[1]/following::div[2]</value>
      <webElementGuid>b38bfd7c-014b-49e2-8f52-cd8e8b1d5bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[2]/following::div[4]</value>
      <webElementGuid>4c40fde4-0836-4dd1-9f66-87ee4a634160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan'])[1]/preceding::div[2]</value>
      <webElementGuid>78c30c15-d60c-4af5-a5db-33af3946c245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div</value>
      <webElementGuid>645afa39-db1e-4b8b-ac82-086bc99485bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Group-PANEL:h:' and (text() = 'Berdasarkan' or . = 'Berdasarkan')]</value>
      <webElementGuid>7319ec5d-2848-40ca-aee8-4e3d7997578e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
