<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>11fd19d3-99f0-42dc-9df0-6cda31434984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Block-PANEL:s:']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>43b7a30b-5be8-43c6-b518-0bfaa5fa2d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>533bea1f-314a-433c-8bc0-6d7056419d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f18852d-39cd-41c2-a230-9e8692037c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c614a70-e778-4f74-99d8-35a5986c7290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc5989b4-5639-46e5-97e0-833d0d54a448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7964bbfb-b8f3-4c95-bf97-6a4879d031ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f6529c9-a62f-4939-a605-d46e8d311d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c2ccb7ab-523c-42dc-b1d9-9bb81cb4b4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7a8fed66-f7f2-4ca5-b535-5545d97063d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.src='../api/app/Views/Preview.html?_rand_=lro284v9&amp;batal_by=all&amp;cabang=370&amp;file=pdf&amp;filter_by=all_bat&amp;grpField=product_code&amp;grpFieldDesc=Produk&amp;grpFieldFrom=AD1&amp;grpFieldTo=AD5&amp;grpTable=sv_para_product&amp;grpTableDesc=descr&amp;grpTableField=product_code&amp;grpTableFilter=product_code%253E%253D%27%27&amp;input_date1=%222025-01-14T00%3A00%3A00.000+0700%22&amp;input_date2=%222025-01-14T00%3A00%3A00.000+0700%22&amp;jenlap=bat&amp;key=bjbkhrlq&amp;masa_berlaku=&amp;method=POST&amp;mode=I&amp;module=SVRP0005&amp;orderBy=4&amp;page=all&amp;pengguna1=0-001&amp;pengguna2=487-YUS&amp;pnamabank=BANK%2520SINERGI%2520PRAKARSA%2520UTAMA&amp;progid=http%3A%2F%2F192.168.1.239%3A8080%2FCoreMain%2Fapi%2Fpublic%2Fwebarb%2Fmain%2Freport%2F&amp;saldo1=0.00&amp;saldo2=0.00&amp;tglquery=%222025-01-14T00%3A00%3A00.000+0700%22&amp;title=LAPORAN%2520DANA%2520TABUNGAN%2520DITAHAN%2520DAN%2520PEMBATALANNYA&amp;Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlKyIsImlhdCI6MTc1Mzg0MTA3NywiZXhwIjoxNzUzOTI3NDc3LCJicm4iOiIzNzAiLCJvZmMiOm51bGwsInVpZCI6MjIzNSwiaW5tIjoiSFVCIiwidXNyIjoiSFVCRVJUVVMiLCJ1Zm4iOiJIVUJFUlRVUyBLIDEiLCJkZXAiOjY5LCJsdmwiOjYwNzQsImFkbSI6ZmFsc2UsIm9wciI6ZmFsc2UsIm9kdCI6IjIwMjUtMDEtMTQiLCJjdHIiOiJZIiwiY3NsIjoiMDAwIiwibG9nIjoiMjAyNS0wNy0zMCAwOTowNDozNyIsImNpZCI6ImNiMTc0M3VxIiwicGlkIjoiOHo4MnZobXIiLCJpcGEiOiIxOTIuMTY4LjEwLjQzIiwiYXBwIjoiQ1AiLCJlbmMiOmZhbHNlLCJ2ZXIiOiIyMDI1LTA3LTA3In0.HIM5O8R-UJfdYRQW5tds1YnJ_CuBm5XYJZkefUEJhEw'.replace('&amp;','#')</value>
      <webElementGuid>d2d50151-5f8b-4780-aa48-1a4b60e93eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../api/app/Views/Preview.html?_rand_=lro284v9#batal_by=all&amp;cabang=370&amp;file=pdf&amp;filter_by=all_bat&amp;grpField=product_code&amp;grpFieldDesc=Produk&amp;grpFieldFrom=AD1&amp;grpFieldTo=AD5&amp;grpTable=sv_para_product&amp;grpTableDesc=descr&amp;grpTableField=product_code&amp;grpTableFilter=product_code%253E%253D%27%27&amp;input_date1=%222025-01-14T00%3A00%3A00.000+0700%22&amp;input_date2=%222025-01-14T00%3A00%3A00.000+0700%22&amp;jenlap=bat&amp;key=bjbkhrlq&amp;masa_berlaku=&amp;method=POST&amp;mode=I&amp;module=SVRP0005&amp;orderBy=4&amp;page=all&amp;pengguna1=0-001&amp;pengguna2=487-YUS&amp;pnamabank=BANK%2520SINERGI%2520PRAKARSA%2520UTAMA&amp;progid=http%3A%2F%2F192.168.1.239%3A8080%2FCoreMain%2Fapi%2Fpublic%2Fwebarb%2Fmain%2Freport%2F&amp;saldo1=0.00&amp;saldo2=0.00&amp;tglquery=%222025-01-14T00%3A00%3A00.000+0700%22&amp;title=LAPORAN%2520DANA%2520TABUNGAN%2520DITAHAN%2520DAN%2520PEMBATALANNYA&amp;Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlKyIsImlhdCI6MTc1Mzg0MTA3NywiZXhwIjoxNzUzOTI3NDc3LCJicm4iOiIzNzAiLCJvZmMiOm51bGwsInVpZCI6MjIzNSwiaW5tIjoiSFVCIiwidXNyIjoiSFVCRVJUVVMiLCJ1Zm4iOiJIVUJFUlRVUyBLIDEiLCJkZXAiOjY5LCJsdmwiOjYwNzQsImFkbSI6ZmFsc2UsIm9wciI6ZmFsc2UsIm9kdCI6IjIwMjUtMDEtMTQiLCJjdHIiOiJZIiwiY3NsIjoiMDAwIiwibG9nIjoiMjAyNS0wNy0zMCAwOTowNDozNyIsImNpZCI6ImNiMTc0M3VxIiwicGlkIjoiOHo4MnZobXIiLCJpcGEiOiIxOTIuMTY4LjEwLjQzIiwiYXBwIjoiQ1AiLCJlbmMiOmZhbHNlLCJ2ZXIiOiIyMDI1LTA3LTA3In0.HIM5O8R-UJfdYRQW5tds1YnJ_CuBm5XYJZkefUEJhEw</value>
      <webElementGuid>eeb99c34-3249-4b51-be63-a46fb2078444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Block-PANEL:s:&quot;)/iframe[1]</value>
      <webElementGuid>62f62315-b5ba-4977-b793-bf19eab7ae04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Block-PANEL:s:']/iframe</value>
      <webElementGuid>33897fff-75ba-4b95-9eb0-4d468cf148a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPORAN DANA TABUNGAN DITAHAN DAN PEMBATALANNYA (Print Preview)'])[1]/following::iframe[1]</value>
      <webElementGuid>391bbf3d-b6f5-4a89-a1f5-c3752a7a0f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXCEL'])[1]/following::iframe[1]</value>
      <webElementGuid>898efd3b-2327-4307-b1db-3ae68394f3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVRP0005'])[1]/preceding::iframe[1]</value>
      <webElementGuid>a08d2f8b-ea65-4481-ab1f-af813a5dfddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVRP0005'])[2]/preceding::iframe[1]</value>
      <webElementGuid>fa87e85b-c6bf-4cb6-9beb-69558fe095a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c01f7985-8789-4749-8a53-c9b10da363c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../api/app/Views/Preview.html?_rand_=lro284v9#batal_by=all&amp;cabang=370&amp;file=pdf&amp;filter_by=all_bat&amp;grpField=product_code&amp;grpFieldDesc=Produk&amp;grpFieldFrom=AD1&amp;grpFieldTo=AD5&amp;grpTable=sv_para_product&amp;grpTableDesc=descr&amp;grpTableField=product_code&amp;grpTableFilter=product_code%253E%253D%27%27&amp;input_date1=%222025-01-14T00%3A00%3A00.000+0700%22&amp;input_date2=%222025-01-14T00%3A00%3A00.000+0700%22&amp;jenlap=bat&amp;key=bjbkhrlq&amp;masa_berlaku=&amp;method=POST&amp;mode=I&amp;module=SVRP0005&amp;orderBy=4&amp;page=all&amp;pengguna1=0-001&amp;pengguna2=487-YUS&amp;pnamabank=BANK%2520SINERGI%2520PRAKARSA%2520UTAMA&amp;progid=http%3A%2F%2F192.168.1.239%3A8080%2FCoreMain%2Fapi%2Fpublic%2Fwebarb%2Fmain%2Freport%2F&amp;saldo1=0.00&amp;saldo2=0.00&amp;tglquery=%222025-01-14T00%3A00%3A00.000+0700%22&amp;title=LAPORAN%2520DANA%2520TABUNGAN%2520DITAHAN%2520DAN%2520PEMBATALANNYA&amp;Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlKyIsImlhdCI6MTc1Mzg0MTA3NywiZXhwIjoxNzUzOTI3NDc3LCJicm4iOiIzNzAiLCJvZmMiOm51bGwsInVpZCI6MjIzNSwiaW5tIjoiSFVCIiwidXNyIjoiSFVCRVJUVVMiLCJ1Zm4iOiJIVUJFUlRVUyBLIDEiLCJkZXAiOjY5LCJsdmwiOjYwNzQsImFkbSI6ZmFsc2UsIm9wciI6ZmFsc2UsIm9kdCI6IjIwMjUtMDEtMTQiLCJjdHIiOiJZIiwiY3NsIjoiMDAwIiwibG9nIjoiMjAyNS0wNy0zMCAwOTowNDozNyIsImNpZCI6ImNiMTc0M3VxIiwicGlkIjoiOHo4MnZobXIiLCJpcGEiOiIxOTIuMTY4LjEwLjQzIiwiYXBwIjoiQ1AiLCJlbmMiOmZhbHNlLCJ2ZXIiOiIyMDI1LTA3LTA3In0.HIM5O8R-UJfdYRQW5tds1YnJ_CuBm5XYJZkefUEJhEw']</value>
      <webElementGuid>f3f2ce73-4987-413c-93ba-7eb8fefcc4ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
