<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Favorites</name>
   <tag></tag>
   <elementGuidId>6093b4fa-2c54-4dd0-87c0-0eeeb8975d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_stkMain >> internal:text=&quot;Favorites&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63ffb22e-241a-4174-9980-67d1713ed3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Stacks-CAPTION:a:b</value>
      <webElementGuid>066c9441-cd9f-402d-b6fc-521b5567daad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-stacks-caption xui-title-node     xui-custom</value>
      <webElementGuid>e61acf0e-3040-42dd-8453-834b8bdf76e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>60ee3dd0-6e5b-4eb6-8470-d89c93203e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Stacks-CAPTION:a:b&quot;)</value>
      <webElementGuid>d8b6d727-da5a-4e08-a719-a8ebcaf01267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      <webElementGuid>461af755-ee19-49d2-ba71-cf733b81f5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Stacks-IBWRAP:a:b']/span[5]</value>
      <webElementGuid>c9f4aa53-885b-44a9-bd0e-1b9797bee984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[3]/following::span[14]</value>
      <webElementGuid>7a54f9bd-e81e-43c0-a022-db27052b7d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[2]/following::span[25]</value>
      <webElementGuid>ace5b553-fc77-432c-beab-3e62bfef112b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferences'])[2]/preceding::span[10]</value>
      <webElementGuid>87cadde7-f52a-45a1-a90d-9ccb24836154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::span[24]</value>
      <webElementGuid>671de4d8-d799-4816-a13e-a1f4d4233fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span/div/span[5]</value>
      <webElementGuid>063f47fe-c3da-419c-8841-1103a75a6d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Stacks-CAPTION:a:b' and (text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>e14fd5f6-47f6-4173-83eb-61030479207b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
