<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dana yang sudah tidak diblokir</name>
   <tag></tag>
   <elementGuidId>0f1cf008-d1dd-4125-809d-1f35b6139fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.RadioBox-ITEM:c:b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^Dana yang sudah tidak diblokir$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46f77669-d70f-4a3b-955d-25883e4658c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4a71f414-e88a-4efa-a916-84c37cd99a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.RadioBox-ITEM:c:b</value>
      <webElementGuid>d08d4436-4def-4f9a-840d-02fb28b67ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-radiobox-item xui-showfocus         xui-custom</value>
      <webElementGuid>d616fe41-7c26-41d6-b33b-80d34ff3066a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dana yang sudah tidak diblokir</value>
      <webElementGuid>5d616328-c2c2-4837-89af-2aa92318df05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.RadioBox-ITEM:c:b&quot;)</value>
      <webElementGuid>cb7f3638-1d4c-463a-a8c0-90d60d872a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.RadioBox-ITEM:c:b']</value>
      <webElementGuid>bb8120a7-6672-4900-be32-68dddf59decf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.RadioBox-ITEMS:c:']/span[2]</value>
      <webElementGuid>ee25a983-aa1a-4852-a380-bcbfd5fabf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dana yang masih diblokir'])[1]/following::span[1]</value>
      <webElementGuid>b2f7b399-5e85-459d-961f-241c0e457c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Berdasarkan'])[1]/following::span[6]</value>
      <webElementGuid>f6ec5ff5-6d35-483f-81e1-9fb9914f0b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/preceding::span[9]</value>
      <webElementGuid>8a838d62-f550-496a-9dee-d3560640f387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/span[2]</value>
      <webElementGuid>f2026b08-3c80-4881-83ef-ce94c42a403c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.RadioBox-ITEM:c:b' and (text() = 'Dana yang sudah tidak diblokir' or . = 'Dana yang sudah tidak diblokir')]</value>
      <webElementGuid>1d1924a0-32d4-4bd8-b831-4a89314436e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
