<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dana yang sudah tidak diblokir (1)</name>
   <tag></tag>
   <elementGuidId>25203dbb-6be7-479a-8c31-1f7b342f7444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.RadioBox-ITEM:c:b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=/^Dana yang sudah tidak diblokir$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5cf7af1e-25dc-4341-9dac-380d56f53aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>872a4a65-e392-41d2-a403-4892d7a61ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.RadioBox-ITEM:c:b</value>
      <webElementGuid>d7223fa5-d41c-49a6-93a7-ff2bf81851ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-radiobox-item xui-showfocus         xui-custom</value>
      <webElementGuid>deaac142-b211-47b6-8e03-11a13b5c4076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dana yang sudah tidak diblokir</value>
      <webElementGuid>9793479e-cb21-46d8-95c6-c31d31bcb18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.RadioBox-ITEM:c:b&quot;)</value>
      <webElementGuid>43d2d6ed-ad84-48a8-9384-acb74ba48ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.RadioBox-ITEM:c:b']</value>
      <webElementGuid>ff5444d4-35b0-4f03-8803-a86002f015be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.RadioBox-ITEMS:c:']/span[2]</value>
      <webElementGuid>63a1b9a1-4237-4daa-9a5e-6d29854d55a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dana yang masih diblokir'])[1]/following::span[1]</value>
      <webElementGuid>3eef9643-8eb3-4aa5-9033-ed45a4844b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Berdasarkan'])[1]/following::span[6]</value>
      <webElementGuid>12e8f2de-1371-4edd-934e-1cbb72099f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlaku Selamanya'])[1]/preceding::span[16]</value>
      <webElementGuid>3bdb0f16-96ff-4703-81c5-de9d6e067852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/span[2]</value>
      <webElementGuid>960d145c-2f6c-4ac8-a9ef-64a4ca04a81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.RadioBox-ITEM:c:b' and (text() = 'Dana yang sudah tidak diblokir' or . = 'Dana yang sudah tidak diblokir')]</value>
      <webElementGuid>67b8cb09-5c07-4439-bd89-996800c53fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
