<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_MIA TABUNGAN BIASA</name>
   <tag></tag>
   <elementGuidId>8ceebc56-0458-469f-b3e1-ec28b48316fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.List-CAPTION:g:i']/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;MIA TABUNGAN BIASA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f7a9e7a6-2653-4b1d-acb2-81b228981c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MIA TABUNGAN BIASA</value>
      <webElementGuid>cb95b49d-c198-460c-b816-f5b6ef7cae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.List-CAPTION:g:i&quot;)/table[1]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>5a28cd21-5cf8-464d-a46a-d2e879604a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-CAPTION:g:i']/table/tbody/tr/td[3]</value>
      <webElementGuid>99fc7b47-318f-49e8-967a-383d00218b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='='])[44]/following::td[1]</value>
      <webElementGuid>1238ed65-a40d-4105-836e-95fdb9c4e6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M1'])[2]/following::td[2]</value>
      <webElementGuid>e32fb856-2305-47c9-bc7e-358eca74067b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M2'])[2]/preceding::td[1]</value>
      <webElementGuid>d05409c3-93eb-4748-ace6-fb35dfa8fbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='='])[45]/preceding::td[2]</value>
      <webElementGuid>a9c6790d-c471-45d3-9fb0-77ef4d6d8d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span[9]/span[4]/table/tbody/tr/td[3]</value>
      <webElementGuid>cc007aa6-4c39-4dd5-91d8-d7d302709517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'MIA TABUNGAN BIASA' or . = 'MIA TABUNGAN BIASA')]</value>
      <webElementGuid>0b870851-db05-4c02-afcb-6136842bc824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
