<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>6da29d5c-ef96-4617-89b0-ef0a84f3b096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='xui.UI.PageBar-NEXT:b:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04a95f29-b7ef-4ce1-b864-cd529757a875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#2</value>
      <webElementGuid>f311dd4a-ab03-4a6a-a052-f533d37a8894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b6343aa4-1e9d-4721-a3c8-bb4164e280a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.PageBar-NEXT:b:</value>
      <webElementGuid>f62b9123-780e-4ffa-9869-6dcc6d6684ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-a xui-node-a-hover xui-pagebar-next xui-pagebar-next-hover xui-ui-btn xui-ui-btn-hover xui-uibar xui-uibar-hover xui-uigradient xui-uigradient-hover xui-uiborder-radius xui-uiborder-radius-hover xui-custom xui-custom-hover</value>
      <webElementGuid>f3791cc7-bbcb-4d54-8cb1-7da79bc2b9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8114b764-1b02-46df-84e8-344c2bd22aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e9e0233e-a9e8-4cec-b6f0-79f3cee9eb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.PageBar-NEXT:b:&quot;)</value>
      <webElementGuid>2b9a9a00-ab36-4819-98b1-42c843f4080b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='xui.UI.PageBar-NEXT:b:']</value>
      <webElementGuid>f9f2ef5b-04b6-4496-8180-4b844d1105a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.PageBar:b:']/a[4]</value>
      <webElementGuid>e2047c83-8a03-42e5-9d19-9562c69eba05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[2]</value>
      <webElementGuid>5d9c4631-bdde-4568-bd1a-fe45e875b8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::a[4]</value>
      <webElementGuid>8f01a13b-e845-46d1-ae56-bef25bf0ff3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAFTAR PENCARIAN NASABAH'])[1]/following::a[5]</value>
      <webElementGuid>0fec0ae5-a218-4dc6-a177-9377c4b36f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan Semua Data'])[1]/preceding::a[3]</value>
      <webElementGuid>7ce8a12e-b600-4173-bad2-25b6ac04c9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/preceding::a[3]</value>
      <webElementGuid>98625b6f-07ad-4724-a765-0647b2e988e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#2')])[2]</value>
      <webElementGuid>89b3cb7b-4e81-4050-beaf-6997d35a91ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a[4]</value>
      <webElementGuid>58b81945-c12b-4b0c-ba54-3674c95143fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#2' and @id = 'xui.UI.PageBar-NEXT:b:' and @title = '2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>7ecbd7f7-aff6-4dd5-8421-83bc4e874718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
