<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>8bd71ca6-3da1-4461-87dc-4d51c0f17cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='xui.UI.PageBar-LAST:b:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;3&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfd52166-7af2-4df4-82c2-e0d4fa0e6f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#3</value>
      <webElementGuid>a526e7fd-75d8-41cb-b02a-a3849d42d0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b0e1febd-c1f3-4ea4-ad27-733d019d537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.PageBar-LAST:b:</value>
      <webElementGuid>48538ec3-8f5d-4252-b2d1-5b405b19b40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-a xui-node-a-hover xui-pagebar-last xui-pagebar-last-hover xui-ui-btn xui-ui-btn-hover xui-uibar xui-uibar-hover xui-uigradient xui-uigradient-hover xui-uiborder-radius xui-uiborder-radius-hover xui-custom xui-custom-hover</value>
      <webElementGuid>4f6271d5-9914-4085-9378-b76617f1a554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>53a8e40d-1d0a-4317-b879-a1852007b40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d0c7aec5-cf1f-4db5-98f6-39957054a07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.PageBar-LAST:b:&quot;)</value>
      <webElementGuid>195d7a14-3aa7-4f2e-86d7-1dd6b4dff882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='xui.UI.PageBar-LAST:b:']</value>
      <webElementGuid>0d56e196-ee1c-4a02-a0c9-25835fa05b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.PageBar:b:']/a[6]</value>
      <webElementGuid>4bb9b17a-bc0d-47c4-9201-728b72fa1451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'3')])[2]</value>
      <webElementGuid>00cd6b3e-538b-4200-b722-972d0a0d8ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::a[6]</value>
      <webElementGuid>cec7f1a3-3e80-4782-bb46-0c8b1765f6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAFTAR PENCARIAN NASABAH'])[1]/following::a[7]</value>
      <webElementGuid>e0dbec9d-9597-4b98-8c81-c71a7c327562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan Semua Data'])[1]/preceding::a[1]</value>
      <webElementGuid>af111a3a-c239-485b-a266-e3942d9311cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/preceding::a[1]</value>
      <webElementGuid>2d31a138-8130-4db3-bd02-ef83018106f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#3')])[2]</value>
      <webElementGuid>33ad3110-fef5-4518-94af-ea88f0a1622c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a[6]</value>
      <webElementGuid>fed164d6-ae22-4bda-982e-c0f8739e231c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#3' and @id = 'xui.UI.PageBar-LAST:b:' and @title = '3' and (text() = '3' or . = '3')]</value>
      <webElementGuid>37958cb6-1bbc-462a-9852-87b4d09e7dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
