<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AD3 - TABUNGAN BERJANGKA STANDART</name>
   <tag></tag>
   <elementGuidId>c9302370-7ebd-4c83-970d-a4c8f352f189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.List-CAPTION:e:c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AD3 - TABUNGAN BERJANGKA STANDART&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eac641d3-a9ad-4a79-90bc-e639ec4d1803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.List-CAPTION:e:c</value>
      <webElementGuid>577e622e-99c8-4c03-949c-a609bc8fe717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-list-caption     xui-custom</value>
      <webElementGuid>71f337d8-c6d6-499c-83ac-5dd62aa1dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AD3 - TABUNGAN BERJANGKA STANDART</value>
      <webElementGuid>971ad9a5-99a5-4481-bef1-7993b2536ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.List-CAPTION:e:c&quot;)</value>
      <webElementGuid>cc375021-ecc8-419c-afbf-5759f6305b54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-CAPTION:e:c']</value>
      <webElementGuid>3d2cdabf-a843-4206-8d4d-539f34eaaa4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.List-ITEM:e:c']/span[4]</value>
      <webElementGuid>a1df34ea-0325-49bc-8ffb-5fedb011d849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AD1 - TABUNGAN PERORANGAN'])[1]/following::span[8]</value>
      <webElementGuid>786f21c9-2465-478e-b06d-d2d16c381a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBERTUS KENNETH'])[2]/following::span[22]</value>
      <webElementGuid>e363b070-636a-4694-baf8-fcf82e47467d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AD4 - TABUNGAN BERJANGKA HADIAH'])[1]/preceding::span[7]</value>
      <webElementGuid>5dbfc1b2-3a88-4de6-b1ff-0039b526a336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AD5 - TABUNGAN BERJANGKA KENDARAAN'])[1]/preceding::span[15]</value>
      <webElementGuid>fa3d179d-5fbe-4ba9-b284-b64d80a79b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AD3 - TABUNGAN BERJANGKA STANDART']/parent::*</value>
      <webElementGuid>31a72874-cb97-4fa4-9bd4-2b28f4c518b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span[3]/span[4]</value>
      <webElementGuid>63bbf30d-e409-4b56-9f6b-d37db10ab142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.List-CAPTION:e:c' and (text() = 'AD3 - TABUNGAN BERJANGKA STANDART' or . = 'AD3 - TABUNGAN BERJANGKA STANDART')]</value>
      <webElementGuid>793b6a4a-0c3a-40e7-8b1e-fd4bea85567a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
