<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1. Copy URL berikut dan paste di Tab Br_6170e0</name>
   <tag></tag>
   <elementGuidId>2f4733b2-1e35-4549-bb78-7a5eb56894bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:u:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1. Copy URL berikut dan paste di Tab Browser baru: chrome://flags/#enable-webrtc&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>614f0892-3b37-46d5-9dc3-a0d8331eefc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a8d93c6c-9d51-4f67-b9cb-668bd76e8b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:u:</value>
      <webElementGuid>667fd25d-4d31-4879-aa3f-fac2914f8c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer  xui-ui-ctrl xui-ui-selectable      xui-custom</value>
      <webElementGuid>2feb76b4-b047-4388-b597-5bfd5a7fa91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)</value>
      <webElementGuid>8a3b1c8d-1c9c-45d4-9cc4-fca75365238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:u:&quot;)</value>
      <webElementGuid>ae5ef38e-3ceb-49e6-8424-5283254eaa07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:u:']</value>
      <webElementGuid>9fdadc68-1d15-4eb0-81f7-d78f74ff0428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-PANEL:h:']/div[2]</value>
      <webElementGuid>0d3a081b-4008-4022-a4ba-d6de840bd9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O K'])[2]/following::div[1]</value>
      <webElementGuid>239c13fc-684d-4587-a7e0-14d04b78b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Tidak Terdeteksi'])[1]/following::div[8]</value>
      <webElementGuid>ddaea64e-c96a-46ea-84c1-bfaf364b035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Copy URL berikut dan paste di Tab Browser baru:']/parent::*</value>
      <webElementGuid>4d8081d0-fdaf-4719-864b-3c419fa0edfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[17]/span/span/div[2]/div/div/div[2]</value>
      <webElementGuid>665adcf3-2c03-4fab-9ca9-0caa1fa9b08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:u:' and (text() = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)' or . = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)')]</value>
      <webElementGuid>cdc51af6-448f-421e-8870-b9a8aad69ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
