<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SVMA0003</name>
   <tag></tag>
   <elementGuidId>d7e24a43-de2e-45c4-aa5f-727fa45d27eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.ButtonViews-CAPTION:a:b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SVMA0003&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>568c936f-3d05-413a-9a68-c3c0d24106e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-CAPTION:a:b</value>
      <webElementGuid>788c865c-2046-4844-bae2-976a9c0b92e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-buttonviews-caption xui-title-node     xui-custom</value>
      <webElementGuid>0d2c0f77-85a0-4cf6-8d12-b6bf9bbb5f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SVMA0003</value>
      <webElementGuid>a7ab41a3-f6bb-4b6e-a0c9-679e59322906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-CAPTION:a:b&quot;)</value>
      <webElementGuid>93e41cbd-211d-4f57-999b-53c499c738ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-CAPTION:a:b']</value>
      <webElementGuid>d63e8c0c-e060-4d1e-a1d5-48f721c7a42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:a:b']/span[4]</value>
      <webElementGuid>2bc18019-57e1-49fe-8b34-66e9d2bae7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVMA0008'])[2]/following::span[13]</value>
      <webElementGuid>9b5dce4f-6d93-408a-86d8-aa12572aa46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVMA0008'])[1]/following::span[23]</value>
      <webElementGuid>f2cd0a3b-4e5b-411e-8481-4d4bfc841bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connecting User'])[1]/preceding::span[34]</value>
      <webElementGuid>af121e38-aaec-40d3-a674-45d47a0d4826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SVMA0003']/parent::*</value>
      <webElementGuid>010cab3a-0467-407c-aeea-ee18ef8b7c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span[2]/span/span/span/div/span[4]</value>
      <webElementGuid>06bdac27-c0e5-40f7-9ed6-059c33ec9f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.ButtonViews-CAPTION:a:b' and (text() = 'SVMA0003' or . = 'SVMA0003')]</value>
      <webElementGuid>b95f8aa8-f9ca-416b-be5b-f30dcb024090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
