<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SVMA0008</name>
   <tag></tag>
   <elementGuidId>d773069a-af04-4b53-9455-5f0642b03250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.ButtonViews-CAPTION:a:a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#buttonbar >> internal:text=&quot;SVMA0008&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab41690a-9b12-4780-a686-8ab951878801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ButtonViews-CAPTION:a:a</value>
      <webElementGuid>8a407fa9-c905-4c3f-8a8e-fe7d41dc30f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-buttonviews-caption xui-title-node     xui-custom</value>
      <webElementGuid>aafceec0-21b4-4f80-b8b7-d969bcb08673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SVMA0008</value>
      <webElementGuid>7f403779-009c-4ec2-8201-be4e3c1f2d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ButtonViews-CAPTION:a:a&quot;)</value>
      <webElementGuid>35fd33d2-835c-43a5-a995-a96b7f3b2f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ButtonViews-CAPTION:a:a']</value>
      <webElementGuid>a0628b44-82ca-4cf7-b09e-924c887e8565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ButtonViews-IBWRAP:a:a']/span[4]</value>
      <webElementGuid>c4f3867f-02f4-493c-810c-4bed808ed0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVMA0003'])[1]/following::span[10]</value>
      <webElementGuid>8de772d9-33a5-437b-85c5-cf20c441378d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/following::span[25]</value>
      <webElementGuid>f147ee97-e0ed-42c0-b391-d509388716fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SVMA0003'])[2]/preceding::span[9]</value>
      <webElementGuid>35847a61-6887-4e5e-b28e-b5bd9866a142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connecting User'])[1]/preceding::span[47]</value>
      <webElementGuid>2343cd97-e71e-4a6d-b9c8-527f0203b38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SVMA0008']/parent::*</value>
      <webElementGuid>36bc0074-30a0-441b-a5cf-d9b7ea15c127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/span/span/span/div/span[4]</value>
      <webElementGuid>5cd23ea1-e4f3-4b86-b850-309893790dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.ButtonViews-CAPTION:a:a' and (text() = 'SVMA0008' or . = 'SVMA0008')]</value>
      <webElementGuid>765e77c4-0092-423c-ae91-fa2635deb67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
